config_version = 14

[bar.default]
background_opacity = 0.60999998636543751
center = [ "clock", "notifications" ]
concave_edge_corners = false
end = [ "tray", "network", "bluetooth", "volume", "battery", "session" ]
start = [ "control-center", "workspaces", "media" ]
widget_spacing = 10

[location]
address = "Bogota"

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.00006103515625
    cy = 807.00006103515625
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
temperature_day = 5600

[shell]
telemetry_enabled = true

    [shell.animation]
    speed = 2.0000000298023224

    [shell.panel]
    transparency_mode = "glass"

[theme]
builtin = "Nord"
community_palette = "Zenbones"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-monochrome"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "ghostty", "hyprland", "kcolorscheme", "kitty", "qt" ]
    community_ids = [ "zen-browser", "neovim" ]

[wallpaper.default]
path = "/home/sva/Pictures/ascii_adam.png"

[wallpaper.last]
path = "/home/sva/Pictures/ascii_adam.png"

[wallpaper.monitors.eDP-1]
path = "/home/sva/Pictures/ascii_adam.png"

[[wallpaper.favorite]]
community_palette = "Zenbones"
palette_source = "community"
path = "/home/sva/Pictures/painting_2.png"
theme_mode = "light"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/sva/Pictures/ascii_adam.png"
theme_mode = "dark"
wallpaper_scheme = "m3-monochrome"

[widget.clock]
format = "{: %a %H:%M}"

[widget.control-center]
glyph = "leaf"